version: '3.5'
services:
  slim:
    build:
      context: ./docker/php
      args:
        uid: ${UID}
    volumes:
      - ./slim:/var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - "8000:80"
    networks:
      default:
        aliases:
          - "default"

  nuxt:
    image: node:latest
    working_dir: /home/node/app
    volumes:
      - ./nuxt:/home/node/app
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    networks:
      default:
        aliases:
          - "default"
    command: bash -c "yarn install && yarn dev"

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=slim
    networks:
      default:
        aliases:
          - "default"

networks:
  default:
    name: backend-network